pass arrays to wrapper; several bug fixes

diff --git a/bin/run-sandbox b/bin/run-sandbox
--- a/bin/run-sandbox
+++ b/bin/run-sandbox
@@ -28,7 +28,6 @@ TIMEFORMAT=$'\nReal time: %3R s\nUser time: %3U s\nSys. time: %3S s\nCPU share: 
 separator=$(head -c 12 /dev/urandom | base64 | tee .error.tio)
 wrappers=/srv/wrappers
 timeout=$1
-identifiers='args|lang'
 
 while ((time_left = timeout - SECONDS)) && read_string -N1 action; do case "$action" in
 	D)	# delete file/directory
@@ -43,21 +42,23 @@ while ((time_left = timeout - SECONDS)) && read_string -N1 action; do case "$act
 		[[ $lang =~ ^[0-9A-Za-z_-]+$ ]] && [[ -f $wrappers/$lang ]] || error "The language '$lang' could not be found on the server."
 		echo -en $separator >> .output.tio
 		echo -en $separator >> .debug.tio
-		touch .code.tio .input.tio
-		{ time timeout $time_left "$wrappers/$lang" "${args[@]}"; } 2> >(head -c 128K >> .debug.tio) | head -c 128K >> .output.tio
+		touch .code.tio .input.tio .env.tio
+		{ time BASH_ENV=.env.tio timeout $time_left "$wrappers/$lang" "${args[@]}"; } 2> >(head -c 128K >> .debug.tio) | head -c 128K >> .output.tio
 		status=${PIPESTATUS[0]}
 		printf 'Exit code: %u' $status >> .debug.tio
 		;;
 	U)	# unset variable
 		read_string name
-		unset "$name"
+		unset $name
+		echo unset $name >> .env.tio
 		;;
 	V)	# declare variable
 		read_string name
-		unset "$name"
-		[[ $name =~ ^(identifiers)$ ]] && error "The variable '$name' could not be declared."
+		[[ $name =~ ^(args|lang|TIO_[A-Z_]+)$ ]] || error "The variable '$name' could not be declared."
+		declare -a "$name=()"
 		read_integer length
-		for ((index = 0; index < length; index++)); do read_string "$name[$index]"; done
+		for ((index = 0; index < length; index++)); do read_string $name[$index]; done
+		[[ $name =~ ^TIO_ ]] && declare -p $name >> .env.tio
 		;;
 	*)
 		error "The instruction '$action' is not implemented."
