fixed legacy run script; fixed error output of conf lib

diff --git a/lib/conf b/lib/conf
--- a/lib/conf
+++ b/lib/conf
@@ -4,16 +4,17 @@ conf_dir=/srv/etc
 
 load_conf()
 {
-	for conf_file in $conf_dir/$1 $conf_dir/$1.d/*; do
+	conf_name=$1
+	shift
+	for conf_file in $conf_dir/$conf_name $conf_dir/$conf_name.d/*; do
 		[[ -f "$conf_file" ]] && source "$conf_file" || true
 	done
-	shift
 	for name in "$@"; do
 		NAME=${name^^}
 		if [[ ${!NAME} ]]; then
 			declare -g "$name=${!NAME}"
 		elif ! [[ ${!name} ]]; then
-			echo "$0: error: Variable '$name' must be set in '$conf_dir/$1' or '$conf_dir/$1.d'." >&2
+			echo "$0: error: Variable '$name' must be set in '$conf_dir/$conf_name' or '$conf_dir/$conf_name.d'." >&2
 			exit 1
 		fi
 	done
